DATABASE_HOSTNAME: "localhost"
DATABASE_NAME: "rails_app_development"
DATABASE_USERNAME: "root"
DATABASE_PASSWORD: "password"
REDIS_HOSTNAME: "localhost"
TEST: "ahihi"
RAILS_ENV: "development"
SECRET_KEY_BASE: "9bb462167302ff84eb69f3820e97d80a4155fcba8514feb2fd66bbd512fd77d6d7b9bf26ef3c205ed260f152c93a548ed4ea87a4dd22d3c616bac2db297eb621"
